#!/usr/bin/env bash
#Script will upload file to a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#Assign argument to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

#Disable scrickhost key
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_Key" "$path_to_file" "$username@$ip:~/"
#Checking if file transfer was succesfull
if [ $? -eq 0 ]
then
	echo "Succesfully transfered file"
else
	echo "Failed to tranfer file"
fi
