#!/usr/bin/env bash
# Commands to install nginx and web server
sudo apt-get update
sudo apt-get install nginx

#Add firewall
sudo ufw "Nginx HTTP"

#Write into html directory/return page
echo "Hello World!" | sudo tee /var/www/html/index.html

#To test nginx
sudo nginx -t

# Reload nginx
sudo service nginx restart
