#!/usr/bin/env bash
# Script will print "Best School and Hi on the 9th line"
counter=1
while [ "$counter" -le 10 ];
do
	if [ "$counter" -eq 9 ];
	then
		echo "Best School"
		echo "Hi"

	else
		echo "Best School"
	fi
	((counter++))
done
