#!/usr/bin/env bash
# A Bash script that displays The content of the current directory
# In a list format
for file in *
do
	if [[ ! -h "$file" && ! -d "$file" && ! -r "$file" ]];
then
	name=$(echo "$file" | cut -d'-' -f2-)
	echo "$name"
	fi
done
