#!/usr/bin/env bash
# A Bash script that runs the whoami command on the the first argument passed
# to it. Here am assumming the first command passed to the script is a user
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
